# Compile the live admission blocks, not a copied model of their predicates.
# Also usable with cmake -D... -P for a bounded standalone regression build.
file(READ "${COLD_CELL_SOURCE_ROOT}/Core/GameEngine/Source/GameLogic/AI/AIPathfind.cpp" _path_source)
file(READ "${COLD_CELL_SOURCE_ROOT}/Core/GameEngine/Include/GameLogic/AIPathfind.h" _cell_source)
file(MAKE_DIRECTORY "${COLD_CELL_BINARY_DIR}")
foreach(_kind IN ITEMS Direct Ordinary)
    string(FIND "${_path_source}" "Bool Pathfinder::capture${_kind}PathBatchEntry(" _function)
    if(_function LESS 0)
        message(FATAL_ERROR "Missing ${_kind} capture owner")
    endif()
    string(SUBSTRING "${_path_source}" ${_function} -1 _suffix)
    string(FIND "${_suffix}" "PathfindCell *startCell =" _start)
    if(_start LESS 0)
        message(FATAL_ERROR "Missing ${_kind} cell admission")
    endif()
    string(SUBSTRING "${_suffix}" ${_start} -1 _block)
    string(FIND "${_block}" "\n\t}\n" _end)
    if(_end LESS 0)
        message(FATAL_ERROR "Missing ${_kind} cell rejection boundary")
    endif()
    math(EXPR _length "${_end} + 4")
    string(SUBSTRING "${_block}" 0 ${_length} _block)
    file(WRITE "${COLD_CELL_BINARY_DIR}/${_kind}CellAdmission.inc" "${_block}\nreturn true;\n")
endforeach()
set(_methods "")
foreach(_method IN ITEMS getXIndex getYIndex hasInfo)
    string(REGEX MATCH "[^\n]*${_method}\\(\\) const[^\n]*" _line "${_cell_source}")
    if(NOT _line)
        message(FATAL_ERROR "Missing live cell method ${_method}")
    endif()
    string(APPEND _methods "${_line}\n")
endforeach()
file(WRITE "${COLD_CELL_BINARY_DIR}/CellInfoAccessors.inc" "${_methods}")
if(NOT CMAKE_SCRIPT_MODE_FILE)
    add_executable(core_path_capture_cold_cell_tests "${CMAKE_CURRENT_LIST_DIR}/ColdCellAdmissionTest.cpp")
    target_include_directories(core_path_capture_cold_cell_tests PRIVATE "${COLD_CELL_BINARY_DIR}")
    set_target_properties(core_path_capture_cold_cell_tests PROPERTIES
        CXX_STANDARD 20 CXX_STANDARD_REQUIRED YES CXX_EXTENSIONS NO)
    add_test(NAME core_path_capture_cold_cell_tests COMMAND core_path_capture_cold_cell_tests)
    set_tests_properties(core_path_capture_cold_cell_tests PROPERTIES TIMEOUT 30)
endif()
