include_guard(GLOBAL)

function(rts_add_headless_metric_startup_test target title test_name)
    set(_source "${CMAKE_SOURCE_DIR}/${title}/Code/GameEngine/Source/Common/GameEngine.cpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_source}")
    file(READ "${_source}" _text)
    string(REPLACE "\r\n" "\n" _text "${_text}")
    string(FIND "${_text}" "void startHeadlessSimulationJobsAfterUnsafeInitialization()\n{" _start)
    if(_start LESS 0)
        message(FATAL_ERROR "${title} headless startup entry is missing")
    endif()
    string(SUBSTRING "${_text}" ${_start} -1 _prefix)
    string(FIND "${_prefix}" "\n\tif (rts::GetPipelineExecutionMode()" _end)
    if(_end LESS 0)
        message(FATAL_ERROR "${title} headless startup metric boundary is missing")
    endif()
    string(SUBSTRING "${_prefix}" 0 ${_end} _prefix)
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/HeadlessMetricStartupUnderTest.inc"
        CONTENT "${_prefix}\n}\n")
    target_sources(${target} PRIVATE
        "${CMAKE_SOURCE_DIR}/Core/Tools/Stage5PerformanceFixtureTest/HeadlessMetricStartupTitleTest.cpp")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
    add_test(NAME ${test_name} COMMAND ${target} --headless-metric-startup)
    set_tests_properties(${test_name} PROPERTIES TIMEOUT 30)
endfunction()
