include_guard(GLOBAL)

function(rts_add_headless_metric_startup_test target title test_name)
    set(_source "${CMAKE_SOURCE_DIR}/${title}/Code/GameEngine/Source/Common/GameEngine.cpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_source}")
    file(READ "${_source}" _text)
    string(REPLACE "\r\n" "\n" _text "${_text}")
    string(FIND "${_text}" "void startHeadlessSimulationJobsAfterUnsafeInitialization()\n{" _start)
    if(_start LESS 0)
        message(FATAL_ERROR "${title} headless startup entry is missing")
    endif()
    string(SUBSTRING "${_text}" ${_start} -1 _prefix)
    if(title STREQUAL "GeneralsMD")
        string(FIND "${_prefix}" "\n#if !defined(_WIN64)" _end)
    else()
        string(FIND "${_prefix}" "\n\tif (rts::GetPipelineExecutionMode()" _end)
    endif()
    if(_end LESS 0)
        message(FATAL_ERROR "${title} headless startup metric boundary is missing")
    endif()
    string(SUBSTRING "${_prefix}" 0 ${_end} _prefix)
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/HeadlessMetricStartupUnderTest.inc"
        CONTENT "${_prefix}\n}\n")
    target_sources(${target} PRIVATE
        "${CMAKE_SOURCE_DIR}/Core/Tools/Stage5PerformanceFixtureTest/HeadlessMetricStartupTitleTest.cpp")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
    add_test(NAME ${test_name} COMMAND ${target} --headless-metric-startup)
    set_tests_properties(${test_name} PROPERTIES TIMEOUT 30)
    if(title STREQUAL "GeneralsMD")
        string(FIND "${_text}" "const char *headlessSimulationModeName(" _startup_begin)
        string(FIND "${_text}" "void printHeadlessSimulationJobMetrics(" _startup_end)
        if(_startup_begin LESS 0 OR _startup_end LESS _startup_begin)
            message(FATAL_ERROR "${title} complete headless startup boundary is missing")
        endif()
        math(EXPR _startup_length "${_startup_end} - ${_startup_begin}")
        string(SUBSTRING "${_text}" ${_startup_begin} ${_startup_length} _startup)
        file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/HeadlessSimulationStartupUnderTest.inc"
            CONTENT "${_startup}")
        target_sources(${target} PRIVATE
            "${CMAKE_SOURCE_DIR}/Core/Tools/Stage5PerformanceFixtureTest/HeadlessSimulationStartupTitleTest.cpp")
        foreach(_mode parallel shadow serial)
            add_test(NAME zh_headless_simulation_startup_${_mode}_tests
                COMMAND ${target} --headless-simulation-startup ${_mode} parallel)
            set_tests_properties(zh_headless_simulation_startup_${_mode}_tests PROPERTIES TIMEOUT 30)
        endforeach()
        add_test(NAME zh_headless_simulation_startup_serial_pipeline_tests
            COMMAND ${target} --headless-simulation-startup parallel serial)
        set_tests_properties(zh_headless_simulation_startup_serial_pipeline_tests PROPERTIES TIMEOUT 30)
    endif()
endfunction()
