include_guard(GLOBAL)

function(rts_add_performance_receipt_owner_bridge_test target title test_name)
    set(_source "${CMAKE_SOURCE_DIR}/${title}/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_source}")
    file(READ "${_source}" _text)
    string(REPLACE "\r\n" "\n" _text "${_text}")
    set(_start_marker "rts::LiveSimulationPhaseOwnerCallbacks GameLogic::makeStage5PhaseGraphCallbacks()")
    set(_end_marker "Bool GameLogic::runOwnerIntakePhase(")
    string(FIND "${_text}" "${_start_marker}" _start)
    if(_start LESS 0)
        message(FATAL_ERROR "${title} phase owner callback factory is missing")
    endif()
    string(SUBSTRING "${_text}" ${_start} -1 _tail)
    string(LENGTH "${_start_marker}" _marker_length)
    string(SUBSTRING "${_tail}" ${_marker_length} -1 _after_start)
    string(FIND "${_after_start}" "${_start_marker}" _duplicate_start)
    string(FIND "${_tail}" "${_end_marker}" _end)
    string(FIND "${_text}" "${_end_marker}" _first_end)
    if(NOT _duplicate_start EQUAL -1 OR _end LESS 0 OR _first_end LESS _start)
        message(FATAL_ERROR "${title} phase owner method boundaries are ambiguous")
    endif()
    string(SUBSTRING "${_tail}" ${_end} -1 _end_tail)
    string(LENGTH "${_end_marker}" _end_marker_length)
    string(SUBSTRING "${_end_tail}" ${_end_marker_length} -1 _after_end)
    string(FIND "${_after_end}" "${_end_marker}" _duplicate_end)
    if(NOT _duplicate_end EQUAL -1)
        message(FATAL_ERROR "${title} phase owner intake boundary is duplicated")
    endif()
    string(SUBSTRING "${_tail}" 0 ${_end} _methods)
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/PerformanceReceiptOwnerBridgeTitleMethods.inc"
        CONTENT "${_methods}")
    target_sources(${target} PRIVATE
        "${CMAKE_SOURCE_DIR}/Core/Tools/Stage5PerformanceFixtureTest/PerformanceReceiptOwnerBridgeTitleTest.cpp")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
    add_test(NAME ${test_name} COMMAND ${target} --performance-receipt-owner-bridge)
    set_tests_properties(${test_name} PROPERTIES TIMEOUT 30)
endfunction()
