# Verify the native helper's actual post-process CSV and pending artifacts.
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

function(verify_capture mode expected_status should_publish expected_rows expected_dropped)
    set(run_dir "${OUTPUT_DIR}/${mode}")
    file(MAKE_DIRECTORY "${run_dir}")
    file(GLOB previous_artifacts "${run_dir}/shadow-stream-reuse-*.csv*")
    execute_process(COMMAND "${EXECUTABLE}" "${run_dir}" "${mode}"
        RESULT_VARIABLE capture_exit OUTPUT_VARIABLE capture_output ERROR_VARIABLE capture_error)
    if(NOT capture_exit EQUAL 0)
        message(FATAL_ERROR "Shadow capture fixture '${mode}' failed: ${capture_exit}: ${capture_error}")
    endif()
    string(REGEX MATCH "capture_pid=([0-9]+)" capture_pid_match "${capture_output}")
    if(capture_pid_match STREQUAL "")
        message(FATAL_ERROR "Capture fixture '${mode}' PID missing")
    endif()
    set(capture_pid "${CMAKE_MATCH_1}")
    file(GLOB capture_files "${run_dir}/shadow-stream-reuse-${capture_pid}-*.csv")
    file(GLOB pending_files "${run_dir}/shadow-stream-reuse-${capture_pid}-*.csv.pending")
    foreach(previous_file IN LISTS previous_artifacts)
        list(REMOVE_ITEM capture_files "${previous_file}")
        list(REMOVE_ITEM pending_files "${previous_file}")
    endforeach()
    list(LENGTH capture_files capture_count)
    list(LENGTH pending_files pending_count)
    if(should_publish)
        if(NOT capture_count EQUAL 1 OR NOT pending_count EQUAL 0)
            message(FATAL_ERROR "Expected one published capture for '${mode}', got CSV=${capture_count}, pending=${pending_count}")
        endif()
        list(GET capture_files 0 capture_file)
    else()
        if(NOT capture_count EQUAL 0 OR NOT pending_count EQUAL 1)
            message(FATAL_ERROR "Invalid capture '${mode}' was published or lost: CSV=${capture_count}, pending=${pending_count}")
        endif()
        list(GET pending_files 0 capture_file)
    endif()

    file(STRINGS "${capture_file}" capture_lines)
    list(LENGTH capture_lines line_count)
    math(EXPR expected_line_count "${expected_rows}+2")
    if(NOT line_count EQUAL expected_line_count)
        message(FATAL_ERROR "Capture '${mode}' row count mismatch: expected ${expected_line_count} lines, got ${line_count}")
    endif()
    list(GET capture_lines 0 capture_header)
    if(NOT capture_header MATCHES "^epoch,qpc_begin,qpc_end,qpc_frequency," OR
       NOT capture_header MATCHES "miss_disabled,miss_proof,miss_geometry,miss_transform,miss_vb_generation,miss_ib_generation,miss_range$")
        message(FATAL_ERROR "Capture '${mode}' schema incomplete")
    endif()
    if(expected_rows GREATER 0)
        list(GET capture_lines 1 first_row)
        if(NOT first_row MATCHES "^[0-9]+,([0-9]+),([0-9]+),([0-9]+),")
            message(FATAL_ERROR "Capture '${mode}' first row has malformed QPC fields: ${first_row}")
        endif()
        set(first_begin "${CMAKE_MATCH_1}")
        set(first_end "${CMAKE_MATCH_2}")
        set(qpc_frequency "${CMAKE_MATCH_3}")
    endif()
    math(EXPR footer_index "${expected_rows}+1")
    list(GET capture_lines ${footer_index} capture_footer)
    set(expected_footer "# end,rows=${expected_rows},dropped=${expected_dropped},status=${expected_status}")
    if(NOT capture_footer STREQUAL expected_footer)
        message(FATAL_ERROR "Capture '${mode}' footer mismatch: ${capture_footer}")
    endif()

    if(expected_rows GREATER 0)
        if(should_publish)
            if(first_begin LESS_EQUAL 0 OR first_end LESS_EQUAL first_begin OR qpc_frequency LESS_EQUAL 0)
                message(FATAL_ERROR "Published capture '${mode}' contains invalid QPC values: ${first_row}")
            endif()
        elseif(mode STREQUAL "qpc_fail_begin" OR mode STREQUAL "qpc_zero_begin" OR
               mode STREQUAL "qpc_fail_begin_truncated")
            if(NOT first_begin EQUAL 0)
                message(FATAL_ERROR "Capture '${mode}' did not retain the invalid begin sample")
            endif()
        elseif(mode STREQUAL "qpc_fail_end" OR mode STREQUAL "qpc_zero_end" OR
               mode STREQUAL "unclosed")
            if(NOT first_end EQUAL 0)
                message(FATAL_ERROR "Capture '${mode}' did not retain the invalid or missing end sample")
            endif()
        elseif(mode STREQUAL "end_before_begin")
            if(NOT first_begin EQUAL 200 OR NOT first_end EQUAL 199)
                message(FATAL_ERROR "Capture '${mode}' did not retain the reversed interval")
            endif()
        endif()
    endif()

    if(mode STREQUAL "truncated" OR mode STREQUAL "qpc_fail_begin_truncated")
        list(GET capture_lines 1024 last_row)
        if(NOT last_row MATCHES "^2023,")
            message(FATAL_ERROR "Capture '${mode}' last admitted row missing")
        endif()
        if(mode STREQUAL "truncated" AND NOT first_row MATCHES "^1000,[1-9][0-9]*,[1-9][0-9]*,[1-9][0-9]*,16384,49152,1,dynamic_stream,3,128,384,3,2304,0,0,3,2,2,1,1,768,0,0,1536,0,0,0,0,0,0,1,0,0$")
            message(FATAL_ERROR "Actual export fields differ from the valid truncated row: ${first_row}")
        endif()
    endif()
    message(STATUS "Verified shadow capture '${mode}': ${capture_file}")
endfunction()

verify_capture(complete complete TRUE 1 0)
verify_capture(truncated truncated TRUE 1024 2)
verify_capture(empty empty_capture FALSE 0 0)
verify_capture(qpc_fail_begin invalid_qpc FALSE 1 0)
verify_capture(qpc_zero_begin invalid_qpc FALSE 1 0)
verify_capture(qpc_fail_end invalid_qpc FALSE 1 0)
verify_capture(qpc_zero_end invalid_qpc FALSE 1 0)
verify_capture(end_before_begin invalid_interval FALSE 1 0)
verify_capture(unclosed unclosed_row FALSE 1 0)
verify_capture(qpc_fail_begin_truncated invalid_qpc FALSE 1024 2)
